### ISSUE TITLE
Sobran variables. Además debéis acotarle el ámbito

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/TrabajoGrupalProgram#11]
https://github.com/FcoJavierGlez/TrabajoGrupalProgram/blob/ef831d99e9f97f549b8877aaf4f7d8a290e3e3ac/Java/TestAlmacen.java#L45

**Comment by R4f4Lc** [comment]
1. preguntaString
2. preguntaInt
3. preguntaDouble
@JavierGF00
