### ISSUE TITLE
sobra

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/TrabajoGrupalProgram#15]
https://github.com/FcoJavierGlez/TrabajoGrupalProgram/blob/ef831d99e9f97f549b8877aaf4f7d8a290e3e3ac/Java/almacen/Articulo.java#L195

**Comment by FcoJavierGlez** [comment]
Corregida la línea 195.
Borrado el comentario: //#################     TO STRING     #################\\

Cierro el Issue #15
