### ISSUE TITLE
Usad StringBuilder. Para concatenación es más eficiente

### ISSUE THREAD

**Issue by lmagarin** [FcoJavierGlez/TrabajoGrupalProgram#17]
https://github.com/FcoJavierGlez/TrabajoGrupalProgram/blob/ef831d99e9f97f549b8877aaf4f7d8a290e3e3ac/Java/almacen/Almacen.java#L136

**Comment by R4f4Lc** [comment]
Arreglado

**Comment by lmagarin** [comment]
Cuando hagas el commit añade close  #17
Así podría comprobar la solución directamente
